class CountryCode {
  CountryCode({this.countryName, this.code});
  String countryName;
  String code;

  static List<CountryCode> countries = [
    CountryCode(countryName: 'Afghanistan', code: 'AF'),
    CountryCode(countryName: 'Albania', code: 'AL'),
    CountryCode(countryName: 'Algeria', code: 'DZ'),
    CountryCode(countryName: 'Angola', code: 'AO'),
    CountryCode(countryName: 'Argentina', code: 'AR'),
    CountryCode(countryName: 'Armenia', code: 'AM'),
    CountryCode(countryName: 'Australia', code: 'AU'),
    CountryCode(countryName: 'Austria', code: 'AT'),
    CountryCode(countryName: 'Azerbaijan', code: 'AZ'),
    CountryCode(countryName: 'Bahamas', code: 'BS'),
    CountryCode(countryName: 'Bangladesh', code: 'BD'),
    CountryCode(countryName: 'Belarus', code: 'BY'),
    CountryCode(countryName: 'Belgium', code: 'BE'),
    CountryCode(countryName: 'Belize', code: 'BZ'),
    CountryCode(countryName: 'Benin', code: 'BJ'),
    CountryCode(countryName: 'Bhutan', code: 'BT'),
    CountryCode(countryName: 'Bolivia', code: 'BO'),
    CountryCode(countryName: 'Bosnia and Herzegovina', code: 'BA'),
    CountryCode(countryName: 'Botswana', code: 'BW'),
    CountryCode(countryName: 'Brazil', code: 'BR'),
    CountryCode(countryName: 'Brunei Darussalam', code: 'BN'),
    CountryCode(countryName: 'Bulgaria', code: 'BG'),
    CountryCode(countryName: 'Burkina Faso', code: 'BF'),
    CountryCode(countryName: 'Burundi', code: 'BI'),
    CountryCode(countryName: 'Cambodia', code: 'KH'),
    CountryCode(countryName: 'Cameroon', code: 'CM'),
    CountryCode(countryName: 'Canada', code: 'CA'),
    CountryCode(countryName: 'Central African Republic', code: 'CF'),
    CountryCode(countryName: 'Chad', code: 'TD'),
    CountryCode(countryName: 'Chile', code: 'CL'),
    CountryCode(countryName: 'China', code: 'CN'),
    CountryCode(countryName: 'Colombia', code: 'CO'),
    CountryCode(countryName: 'Congo', code: 'CG'),
    CountryCode(countryName: 'Costa Rica', code: 'CR'),
    CountryCode(countryName: 'Croatia', code: 'HR'),
    CountryCode(countryName: 'Cuba', code: 'CU'),
    CountryCode(countryName: 'Cyprus', code: 'CY'),
    CountryCode(countryName: 'Czechia', code: 'CZ'),
    CountryCode(countryName: 'Democratic Republic of Congo', code: 'CD'),
    CountryCode(countryName: 'Denmark', code: 'DK'),
    CountryCode(countryName: 'Diamond Princess', code: 'DP'),
    CountryCode(countryName: 'Djibouti', code: 'DJ'),
    CountryCode(countryName: 'Dominican Republic', code: 'DO'),
    CountryCode(countryName: 'DR Congo', code: 'CD'),
    CountryCode(countryName: 'Ecuador', code: 'EC'),
    CountryCode(countryName: 'Egypt', code: 'EG'),
    CountryCode(countryName: 'El Salvador', code: 'SV'),
    CountryCode(countryName: 'Equatorial Guinea', code: 'GQ'),
    CountryCode(countryName: 'Eritrea', code: 'ER'),
    CountryCode(countryName: 'Estonia', code: 'EE'),
    CountryCode(countryName: 'Ethiopia', code: 'ET'),
    CountryCode(countryName: 'Falkland Islands', code: 'FK'),
    CountryCode(countryName: 'Fiji', code: 'FJ'),
    CountryCode(countryName: 'Finland', code: 'FI'),
    CountryCode(countryName: 'France', code: 'FR'),
    CountryCode(countryName: 'French Guiana', code: 'GF'),
    CountryCode(countryName: 'French Southern Territories', code: 'TF'),
    CountryCode(countryName: 'Gabon', code: 'GA'),
    CountryCode(countryName: 'Gambia', code: 'GM'),
    CountryCode(countryName: 'Georgia', code: 'GE'),
    CountryCode(countryName: 'Germany', code: 'DE'),
    CountryCode(countryName: 'Ghana', code: 'GH'),
    CountryCode(countryName: 'Greece', code: 'GR'),
    CountryCode(countryName: 'Greenland', code: 'GL'),
    CountryCode(countryName: 'Guatemala', code: 'GT'),
    CountryCode(countryName: 'Guinea', code: 'GN'),
    CountryCode(countryName: 'Guinea-Bissal', code: 'GW'),
    CountryCode(countryName: 'Guyana', code: 'GY'),
    CountryCode(countryName: 'Haiti', code: 'HT'),
    CountryCode(countryName: 'Honduras', code: 'HN'),
    CountryCode(countryName: 'Hong Kong', code: 'HK'),
    CountryCode(countryName: 'Hungary', code: 'HU'),
    CountryCode(countryName: 'Iceland', code: 'IS'),
    CountryCode(countryName: 'India', code: 'IN'),
    CountryCode(countryName: 'Indonesia', code: 'ID'),
    CountryCode(countryName: 'Iran', code: 'IR'),
    CountryCode(countryName: 'Iraq', code: 'IQ'),
    CountryCode(countryName: 'Ireland', code: 'IE'),
    CountryCode(countryName: 'Israel', code: 'IL'),
    CountryCode(countryName: 'Italy', code: 'IT'),
    CountryCode(countryName: 'Ivory Coast', code: 'CI'),
    CountryCode(countryName: 'Jamaica', code: 'JM'),
    CountryCode(countryName: 'Japan', code: 'JP'),
    CountryCode(countryName: 'Jordan', code: 'JO'),
    CountryCode(countryName: 'Kazakhstan', code: 'KZ'),
    CountryCode(countryName: 'Kenya', code: 'KE'),
    CountryCode(countryName: 'Kosovo', code: 'XK'),
    CountryCode(countryName: 'Kuwait', code: 'KW'),
    CountryCode(countryName: 'Kyrgyzstan', code: 'KG'),
    CountryCode(countryName: 'Lao', code: 'LA'),
    CountryCode(countryName: 'Latvia', code: 'LV'),
    CountryCode(countryName: 'Lebanon', code: 'LB'),
    CountryCode(countryName: 'Lesotho', code: 'LS'),
    CountryCode(countryName: 'Liberia', code: 'LR'),
    CountryCode(countryName: 'Libya', code: 'LY'),
    CountryCode(countryName: 'Lithuania', code: 'LT'),
    CountryCode(countryName: 'Luxembourg', code: 'LU'),
    CountryCode(countryName: 'Macedonia', code: 'MK'),
    CountryCode(countryName: 'Madagascar', code: 'MG'),
    CountryCode(countryName: 'Malawi', code: 'MW'),
    CountryCode(countryName: 'Malaysia', code: 'MY'),
    CountryCode(countryName: 'Mali', code: 'ML'),
    CountryCode(countryName: 'Mauritania', code: 'MR'),
    CountryCode(countryName: 'Mexico', code: 'MX'),
    CountryCode(countryName: 'Moldova', code: 'MD'),
    CountryCode(countryName: 'Mongolia', code: 'MN'),
    CountryCode(countryName: 'Montenegro', code: 'ME'),
    CountryCode(countryName: 'Morocco', code: 'MA'),
    CountryCode(countryName: 'Mozambique', code: 'MZ'),
    CountryCode(countryName: 'Myanmar', code: 'MM'),
    CountryCode(countryName: 'Namibia', code: 'NA'),
    CountryCode(countryName: 'Nepal', code: 'NP'),
    CountryCode(countryName: 'Netherlands', code: 'NL'),
    CountryCode(countryName: 'New Caledonia', code: 'NC'),
    CountryCode(countryName: 'New Zealand', code: 'NZ'),
    CountryCode(countryName: 'Nicaragua', code: 'NI'),
    CountryCode(countryName: 'Niger', code: 'NE'),
    CountryCode(countryName: 'Nigeria', code: 'NG'),
    CountryCode(countryName: 'North Korea', code: 'KP'),
    CountryCode(countryName: 'Norway', code: 'NO'),
    CountryCode(countryName: 'Oman', code: 'OM'),
    CountryCode(countryName: 'Pakistan', code: 'PK'),
    CountryCode(countryName: 'Palestine', code: 'PS'),
    CountryCode(countryName: 'Panama', code: 'PA'),
    CountryCode(countryName: 'Papua New Guinea', code: 'PG'),
    CountryCode(countryName: 'Paraguay', code: 'PY'),
    CountryCode(countryName: 'Peru', code: 'PE'),
    CountryCode(countryName: 'Philippines', code: 'PH'),
    CountryCode(countryName: 'Poland', code: 'PL'),
    CountryCode(countryName: 'Portugal', code: 'PT'),
    CountryCode(countryName: 'Puerto Rica', code: 'PR'),
    CountryCode(countryName: 'Qatar', code: 'QA'),
    CountryCode(countryName: 'Republic of Kosovo', code: 'XK'),
    CountryCode(countryName: 'Romania', code: 'RO'),
    CountryCode(countryName: 'Russia', code: 'RU'),
    CountryCode(countryName: 'Rwanda', code: 'RW'),
    CountryCode(countryName: 'Saudi Arabia', code: 'SA'),
    CountryCode(countryName: 'Senegal', code: 'SN'),
    CountryCode(countryName: 'Serbia', code: 'RS'),
    CountryCode(countryName: 'Sierra Leone', code: 'SL'),
    CountryCode(countryName: 'Singapore', code: 'SG'),
    CountryCode(countryName: 'Slovakia', code: 'SK'),
    CountryCode(countryName: 'Slovenia', code: 'SI'),
    CountryCode(countryName: 'Solomon Islands', code: 'SB'),
    CountryCode(countryName: 'Somalia', code: 'SO'),
    CountryCode(countryName: 'South Africa', code: 'ZA'),
    CountryCode(countryName: 'South Korea', code: 'KR'),
    CountryCode(countryName: 'South Sudan', code: 'SS'),
    CountryCode(countryName: 'Spain', code: 'ES'),
    CountryCode(countryName: 'Sri Lanka', code: 'LK'),
    CountryCode(countryName: 'Sudan', code: 'SD'),
    CountryCode(countryName: 'Suriname', code: 'SR'),
    CountryCode(countryName: 'Svalbard and Jan Mayen', code: 'SJ'),
    CountryCode(countryName: 'Swaziland', code: 'SZ'),
    CountryCode(countryName: 'Sweden', code: 'SE'),
    CountryCode(countryName: 'Switzerland', code: 'CH'),
    CountryCode(countryName: 'Syrian Arab Republic', code: 'SY'),
    CountryCode(countryName: 'Taiwan', code: 'TW'),
    CountryCode(countryName: 'Tajikistan', code: 'TJ'),
    CountryCode(countryName: 'Tanzania', code: 'TZ'),
    CountryCode(countryName: 'Thailand', code: 'TH'),
    CountryCode(countryName: 'Timor-Leste', code: 'TL'),
    CountryCode(countryName: 'Togo', code: 'TG'),
    CountryCode(countryName: 'Trinidad and Tobago', code: 'TT'),
    CountryCode(countryName: 'Tunisia', code: 'TN'),
    CountryCode(countryName: 'Turkey', code: 'TR'),
    CountryCode(countryName: 'Turkmenistan', code: 'TM'),
    CountryCode(countryName: 'UAE', code: 'AE'),
    CountryCode(countryName: 'Uganda', code: 'UG'),
    CountryCode(countryName: 'Ukraine', code: 'UA'),
    CountryCode(countryName: 'United Kingdon', code: 'GB'),
    CountryCode(countryName: 'Uruguay', code: 'UY'),
    CountryCode(countryName: 'USA', code: 'US'),
    CountryCode(countryName: 'Uzbekistan', code: 'UZ'),
    CountryCode(countryName: 'Vanuatu', code: 'VU'),
    CountryCode(countryName: 'Venezuela', code: 'VE'),
    CountryCode(countryName: 'Vietnam', code: 'VN'),
    CountryCode(countryName: 'Western Sahara', code: 'EH'),
    CountryCode(countryName: 'Yemen', code: 'YE'),
    CountryCode(countryName: 'Zambia', code: 'ZM'),
    CountryCode(countryName: 'Zimbabwe', code: 'ZW'),
  ];
}
